---
- name: Configure web server
  hosts: www
  gather_facts: False

  vars:
    root_dir: ..

  pre_tasks:
    - name: Debug pre tasks
      ansible.builtin.debug:
        msg: "Pre tasks section"

    - name: ANSIBLE PYTHON | install python fallback if needed
      ansible.builtin.raw: test -e /usr/bin/python || test -e /usr/bin/python3 || (apt -qqy update && apt install -qy python-minimal)
      become: yes
      changed_when: False

    - name: UNPRIVILEGED USERS | Get acl dependency (ansible unprivileged user operations magic)
      ansible.builtin.apt:
        pkg: "acl"
      become: yes

    - name: Gather facts
      ansible.builtin.setup:

  roles:
    - role: "sa-apache"

  tasks:
    - name: Debug tasks
      ansible.builtin.debug:
        msg: "Tasks section"
